package comp6421;

public enum EType {
	ID, ALPHANUM, INTEGER, FLOAT,
	PLUS, MINUS, STAR, SLASH, EQUAL, AND, NOT, OR,
	ASSGN, NOTEQ, LT, GT, LESSEQ, GREATEQ, SEMICOLON, COMMA, DOT,
	OPENPAR, CLOSEPAR, OPENBRACE, CLOSEBRACE, OPENBRACKET, CLOSEBRACKET, CMT, OPENCMT, CLOSECMT,
	RESERVED
	//IF, THEN, ELSE, FOR, CLASS, INT, FLOAT, GET, PUT, RETURN, PROGRAM
}
